# Generated by Django 5.2.8 on 2025-11-25 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_sitebranding_theme_preset_dark_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_tier",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("pro", "Professional"),
                            ("organization", "Organization"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        help_text="Current account tier determining feature access",
                        max_length=20,
                    ),
                ),
                (
                    "payment_provider",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Payment provider name (e.g., 'ryft', 'stripe')",
                        max_length=50,
                    ),
                ),
                (
                    "payment_customer_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Customer ID from payment provider",
                        max_length=255,
                    ),
                ),
                (
                    "payment_subscription_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Subscription ID from payment provider",
                        max_length=255,
                    ),
                ),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("canceled", "Canceled"),
                            ("trialing", "Trialing"),
                            ("incomplete", "Incomplete"),
                            ("incomplete_expired", "Incomplete Expired"),
                            ("unpaid", "Unpaid"),
                            ("none", "None"),
                        ],
                        default="none",
                        help_text="Current subscription status",
                        max_length=30,
                    ),
                ),
                (
                    "subscription_current_period_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the current subscription period ends",
                        null=True,
                    ),
                ),
                (
                    "custom_branding_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user can customize platform branding (Enterprise only)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tier_changed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the account tier was last changed",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
