# Generated by Django 5.2.8 on 2025-11-25 20:56

from django.db import migrations


def create_user_profiles(apps, schema_editor):
    """Create UserProfile for all existing users."""
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("core", "UserProfile")

    # Get all users who don't have a profile yet
    users_without_profiles = User.objects.filter(profile__isnull=True)

    # Create profiles in bulk
    profiles_to_create = [
        UserProfile(user=user, account_tier="free") for user in users_without_profiles
    ]

    UserProfile.objects.bulk_create(profiles_to_create, ignore_conflicts=True)


def reverse_create_user_profiles(apps, schema_editor):
    """Reverse migration - delete all UserProfiles."""
    UserProfile = apps.get_model("core", "UserProfile")
    UserProfile.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_add_user_profile"),
    ]

    operations = [
        migrations.RunPython(create_user_profiles, reverse_create_user_profiles),
    ]
