# Generated by Django 5.2.8 on 2025-12-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_create_profiles_for_existing_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="account_tier",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("pro", "Professional"),
                    ("team_small", "Team Small"),
                    ("team_medium", "Team Medium"),
                    ("team_large", "Team Large"),
                    ("organization", "Organization"),
                    ("enterprise", "Enterprise"),
                ],
                default="free",
                help_text="Current account tier determining feature access",
                max_length=20,
            ),
        ),
    ]
