# Generated by Django 5.2.9 on 2025-12-12 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_add_payment_mandate_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        help_text="Unique invoice number for VAT purposes",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("invoice_date", models.DateField(help_text="Date of invoice")),
                (
                    "payment_provider",
                    models.CharField(
                        default="gocardless",
                        help_text="Payment provider (gocardless, manual, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True, help_text="Payment ID from provider", max_length=255
                    ),
                ),
                (
                    "subscription_id",
                    models.CharField(
                        blank=True,
                        help_text="Subscription ID from provider",
                        max_length=255,
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        help_text="Subscription tier at time of payment", max_length=20
                    ),
                ),
                (
                    "billing_period_start",
                    models.DateField(
                        blank=True, help_text="Start of billing period", null=True
                    ),
                ),
                (
                    "billing_period_end",
                    models.DateField(
                        blank=True, help_text="End of billing period", null=True
                    ),
                ),
                (
                    "amount_ex_vat",
                    models.IntegerField(help_text="Amount excluding VAT in pence"),
                ),
                ("vat_amount", models.IntegerField(help_text="VAT amount in pence")),
                (
                    "amount_inc_vat",
                    models.IntegerField(
                        help_text="Total amount including VAT in pence"
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.2,
                        help_text="VAT rate applied (e.g., 0.20 for 20%)",
                        max_digits=5,
                    ),
                ),
                ("currency", models.CharField(default="GBP", max_length=3)),
                (
                    "customer_email",
                    models.EmailField(
                        help_text="Customer email at time of payment", max_length=254
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True, help_text="Customer name/username", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, help_text="When payment was confirmed", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who made the payment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-invoice_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["invoice_date"], name="core_paymen_invoice_ea049c_idx"
                    ),
                    models.Index(
                        fields=["status"], name="core_paymen_status_8390cc_idx"
                    ),
                    models.Index(
                        fields=["user"], name="core_paymen_user_id_afed17_idx"
                    ),
                ],
            },
        ),
    ]
