# Generated by Django 5.2.7 on 2025-11-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0018_alter_survey_retention_months"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="default_theme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("checktick-light", "CheckTick Light"),
                    ("checktick-dark", "CheckTick Dark"),
                ],
                default="",
                help_text="Default theme for organization (empty = use platform default)",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="theme_dark_css",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Custom CSS for dark theme (overrides preset if provided)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="theme_light_css",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Custom CSS for light theme (overrides preset if provided)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="theme_preset_dark",
            field=models.CharField(
                blank=True,
                default="",
                help_text="DaisyUI preset for dark mode (empty = use platform default)",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="theme_preset_light",
            field=models.CharField(
                blank=True,
                default="",
                help_text="DaisyUI preset for light mode (empty = use platform default)",
                max_length=64,
            ),
        ),
    ]
