# Generated by Django 5.2.8 on 2025-11-15 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0019_add_organization_theme_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=40, null=True
                    ),
                ),
                ("partial_answers", models.JSONField(default=dict)),
                ("current_question_id", models.IntegerField(blank=True, null=True)),
                ("total_questions", models.IntegerField(default=0)),
                ("answered_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_question_answered_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("expires_at", models.DateTimeField()),
                (
                    "access_token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="progress",
                        to="surveys.surveyaccesstoken",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="surveys.survey",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["survey", "user"], name="surveys_sur_survey__e688aa_idx"
                    ),
                    models.Index(
                        fields=["survey", "session_key"],
                        name="surveys_sur_survey__6c8445_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="surveys_sur_expires_3fb7e0_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", False)),
                        fields=("survey", "user"),
                        name="one_progress_per_user_per_survey",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("session_key__isnull", False)),
                        fields=("survey", "session_key"),
                        name="one_progress_per_session_per_survey",
                    ),
                ],
            },
        ),
    ]
