# Generated by Django 5.2.8 on 2025-11-18 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0025_add_llm_conversation_session"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublishedQuestionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "publication_level",
                    models.CharField(
                        choices=[
                            ("organization", "Organization"),
                            ("global", "Global"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("markdown", models.TextField(help_text="Markdown representation")),
                (
                    "attribution",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Attribution metadata (authors, citation, PMID, DOI, license)",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags for categorization and search",
                    ),
                ),
                ("language", models.CharField(default="en", max_length=10)),
                ("version", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("deleted", "Deleted (Soft Delete)"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("import_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization for org-level publications",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surveys.organization",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="published_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_group",
                    models.ForeignKey(
                        help_text="Original QuestionGroup this was published from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_versions",
                        to="surveys.questiongroup",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="questiongroup",
            name="imported_from",
            field=models.ForeignKey(
                blank=True,
                help_text="Source published template if this was imported",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="imported_copies",
                to="surveys.publishedquestiongroup",
            ),
        ),
        migrations.AddIndex(
            model_name="publishedquestiongroup",
            index=models.Index(
                fields=["publication_level", "status"],
                name="surveys_pub_publica_7967bb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="publishedquestiongroup",
            index=models.Index(
                fields=["organization", "status"], name="surveys_pub_organiz_e4ba1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publishedquestiongroup",
            index=models.Index(
                fields=["-created_at"], name="surveys_pub_created_effb35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publishedquestiongroup",
            index=models.Index(
                fields=["-import_count"], name="surveys_pub_import__3c2f6e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="publishedquestiongroup",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("organization__isnull", False),
                        ("publication_level", "organization"),
                    ),
                    ("publication_level", "global"),
                    _connector="OR",
                ),
                name="org_required_for_org_level",
            ),
        ),
    ]
