# Generated by Django 5.2.8 on 2025-11-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0026_published_question_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishedquestiongroup",
            name="show_publisher_credit",
            field=models.BooleanField(
                default=True,
                help_text="Whether to show publisher name/organization in public listings",
            ),
        ),
    ]
