# Generated by Django 5.2.8 on 2025-11-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0027_add_publisher_credit_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="allow_any_authenticated",
            field=models.BooleanField(
                default=False,
                help_text="Allow any authenticated user to access this survey (not just invited users)",
            ),
        ),
        migrations.AddField(
            model_name="surveyaccesstoken",
            name="for_authenticated",
            field=models.BooleanField(
                default=False,
                help_text="True if this token is for authenticated user invitation (not anonymous token)",
            ),
        ),
    ]
