# Generated by Django 5.2.8 on 2025-11-20 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0028_add_authenticated_invite_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="is_original",
            field=models.BooleanField(
                default=True,
                help_text="True if this is the original survey, False if it's a translation",
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="language",
            field=models.CharField(
                default="en",
                help_text="Primary language code (ISO 639-1, e.g., 'en', 'fr', 'es')",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="translated_from",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to the survey this was translated from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="translations",
                to="surveys.survey",
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="translation_group",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="UUID linking translated versions of the same survey",
                max_length=100,
                null=True,
            ),
        ),
    ]
