# Generated by Django 5.2.8 on 2025-11-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0029_add_language_translation_fields"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="surveyquestioncondition",
            name="surveyquestioncondition_single_target",
        ),
        migrations.AlterField(
            model_name="surveyquestioncondition",
            name="action",
            field=models.CharField(
                choices=[
                    ("jump_to", "Jump to target"),
                    ("show", "Show target"),
                    ("skip", "Skip target"),
                    ("end_survey", "End survey"),
                ],
                default="jump_to",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyquestioncondition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("target_group__isnull", True),
                        ("target_question__isnull", False),
                    ),
                    models.Q(
                        ("target_group__isnull", False),
                        ("target_question__isnull", True),
                    ),
                    models.Q(
                        ("action", "end_survey"),
                        ("target_group__isnull", True),
                        ("target_question__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="surveyquestioncondition_single_target",
            ),
        ),
    ]
