# Generated by Django 5.2.8 on 2025-11-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0030_add_end_survey_action"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="surveyquestioncondition",
            name="surveyquestioncondition_single_target",
        ),
        migrations.RemoveField(
            model_name="surveyquestioncondition",
            name="target_group",
        ),
        migrations.AddConstraint(
            model_name="surveyquestioncondition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("target_question__isnull", False),
                    models.Q(
                        ("action", "end_survey"), ("target_question__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="surveyquestioncondition_single_target",
            ),
        ),
    ]
