# Generated by Django 5.2.8 on 2025-11-29 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0031_remove_target_group_from_conditions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyquestioncondition",
            name="action",
            field=models.CharField(
                choices=[
                    ("show", "Show when condition met (hidden by default)"),
                    ("jump_to", "Skip ahead to question"),
                    ("skip", "Hide when condition met"),
                    ("end_survey", "End survey"),
                ],
                default="jump_to",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("small", "Small (5 users)"),
                            ("medium", "Medium (10 users)"),
                            ("large", "Large (20 users)"),
                            ("custom", "Custom (>20 users)"),
                        ],
                        default="small",
                        help_text="Team size tier determining member limit and pricing",
                        max_length=20,
                    ),
                ),
                (
                    "custom_max_members",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum members for custom-sized teams (>20 users)",
                        null=True,
                    ),
                ),
                (
                    "max_surveys",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Maximum number of surveys this team can create",
                    ),
                ),
                (
                    "subscription_id",
                    models.CharField(
                        blank=True,
                        help_text="External subscription reference (payment provider agnostic)",
                        max_length=255,
                    ),
                ),
                (
                    "encrypted_master_key",
                    models.BinaryField(
                        blank=True,
                        help_text="Team master key for administrative recovery (will be encrypted with Vault in Phase 2)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional parent organisation (for org-hosted teams)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teams",
                        to="surveys.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="survey",
            name="team",
            field=models.ForeignKey(
                blank=True,
                help_text="Team this survey belongs to (if any)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="surveys",
                to="surveys.team",
            ),
        ),
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("creator", "Creator"),
                            ("viewer", "Viewer"),
                        ],
                        default="creator",
                        help_text="Role persists if team migrates to organisation",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="surveys.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("team", "user")},
            },
        ),
    ]
