# Generated by Django 5.2.8 on 2025-12-03 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0035_team_org_invitations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="organization",
            name="billing_contact_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Email for billing communications",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="billing_notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Internal notes about billing arrangements",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="billing_type",
            field=models.CharField(
                choices=[
                    ("per_seat", "Per Seat"),
                    ("flat_rate", "Flat Rate"),
                    ("invoice", "Invoice (Manual)"),
                    ("free", "Free (Internal/Trial)"),
                ],
                default="per_seat",
                help_text="How this organization is billed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="organization",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Platform admin who created this organization",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_organizations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="flat_rate_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Fixed monthly price (for flat-rate billing)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this organization is active"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="max_seats",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of seats (null = unlimited)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="payment_customer_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Customer ID from payment provider",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="payment_price_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Custom price ID from payment provider (for per-seat billing)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="payment_subscription_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Subscription ID from payment provider",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="price_per_seat",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price per seat per month (for per-seat billing)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="setup_completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the organization owner completed setup",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="setup_token",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Token for owner invite/setup link",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Setup"),
                    ("active", "Active"),
                    ("past_due", "Past Due"),
                    ("canceled", "Canceled"),
                    ("trialing", "Trialing"),
                ],
                default="pending",
                help_text="Current subscription status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
