# Generated by Django 5.2.9 on 2025-12-06 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0036_organization_billing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
            },
        ),
        migrations.AddField(
            model_name="auditlog",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="message",
            field=models.TextField(
                blank=True, help_text="Human-readable event description"
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="severity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("info", "Information"),
                    ("warning", "Warning"),
                    ("critical", "Critical"),
                ],
                default="info",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user_agent",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="username_attempted",
            field=models.CharField(
                blank=True,
                help_text="Username used in login attempt (for failed logins)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("add", "Add"),
                    ("remove", "Remove"),
                    ("update", "Update"),
                    ("create", "Create"),
                    ("invite", "Invite"),
                    ("key_recovery", "Key Recovery"),
                    ("login_success", "Successful Login"),
                    ("login_failed", "Failed Login Attempt"),
                    ("logout", "Logout"),
                    ("account_locked", "Account Locked"),
                    ("2fa_enabled", "2FA Enabled"),
                    ("2fa_disabled", "2FA Disabled"),
                    ("2fa_verified", "2FA Verification Success"),
                    ("2fa_failed", "2FA Verification Failed"),
                    ("backup_codes_generated", "Backup Codes Generated"),
                    ("backup_code_used", "Backup Code Used"),
                    ("password_changed", "Password Changed"),
                    ("password_reset", "Password Reset Requested"),
                    ("email_changed", "Email Address Changed"),
                    ("user_created", "User Account Created"),
                    ("user_deactivated", "User Account Deactivated"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="scope",
            field=models.CharField(
                choices=[
                    ("organization", "Organization"),
                    ("survey", "Survey"),
                    ("security", "Security"),
                    ("account", "Account"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "-created_at"], name="surveys_aud_action_69938d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["actor", "-created_at"], name="surveys_aud_actor_i_744444_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["severity", "-created_at"],
                name="surveys_aud_severit_960e86_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["ip_address", "-created_at"],
                name="surveys_aud_ip_addr_f66c01_idx",
            ),
        ),
    ]
