# Generated by Django 5.2.9 on 2025-12-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0037_extend_auditlog_for_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="redirect_flow_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="GoCardless redirect flow ID during checkout",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="setup_email_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the checkout invitation email was sent",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="setup_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the setup token expires (30 days default)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("quote_sent", "Quote Sent"),
                    ("pending", "Pending Setup"),
                    ("active", "Active"),
                    ("past_due", "Past Due"),
                    ("canceled", "Canceled"),
                    ("trialing", "Trialing"),
                ],
                default="pending",
                help_text="Current subscription status",
                max_length=20,
            ),
        ),
    ]
