# Generated by Django 5.2.9 on 2025-12-13 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0038_organization_quote_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Owner of the organization (set during checkout completion)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organizations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
