# Generated by Django 5.2.9 on 2026-01-04 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0039_organization_owner_nullable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSubjectRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("access", "Right of Access (Art. 15)"),
                            ("erasure", "Right to Erasure (Art. 17)"),
                            ("rectification", "Right to Rectification (Art. 16)"),
                            ("objection", "Right to Object (Art. 21)"),
                            ("portability", "Right to Data Portability (Art. 20)"),
                            ("restriction", "Right to Restriction (Art. 18)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("referred", "Referred to Controller"),
                            ("responded", "Controller Responded"),
                            ("escalated", "Escalated (Controller Non-Responsive)"),
                            ("frozen", "Response Frozen"),
                            ("resolved", "Resolved"),
                            ("rejected", "Rejected (Invalid Request)"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                (
                    "respondent_email",
                    models.EmailField(
                        help_text="Email address of the person making the request",
                        max_length=254,
                    ),
                ),
                (
                    "receipt_token",
                    models.UUIDField(
                        blank=True,
                        help_text="Receipt token provided by respondent (if available)",
                        null=True,
                    ),
                ),
                (
                    "request_details",
                    models.TextField(
                        help_text="Details of the request as provided by the respondent"
                    ),
                ),
                (
                    "controller_notified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the controller was first notified",
                        null=True,
                    ),
                ),
                (
                    "controller_deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deadline for controller response (30 days from notification)",
                        null=True,
                    ),
                ),
                (
                    "controller_reminder_sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When a reminder was sent to the controller",
                        null=True,
                    ),
                ),
                (
                    "controller_response",
                    models.TextField(
                        blank=True, help_text="Controller's response to the request"
                    ),
                ),
                (
                    "controller_responded_at",
                    models.DateTimeField(
                        blank=True, help_text="When the controller responded", null=True
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(
                        blank=True, help_text="Notes on how the request was resolved"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="When the request was resolved", null=True
                    ),
                ),
                (
                    "escalated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the request was escalated due to controller non-response",
                        null=True,
                    ),
                ),
                (
                    "ico_reported",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this case was reported to the ICO",
                    ),
                ),
                (
                    "ico_reported_at",
                    models.DateTimeField(
                        blank=True, help_text="When reported to ICO", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Data Subject Request",
                "verbose_name_plural": "Data Subject Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="frozen_at",
            field=models.DateTimeField(
                blank=True, help_text="When this response was frozen", null=True
            ),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="frozen_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who froze this response",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="frozen_responses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="frozen_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason for freezing (e.g., 'Data subject request pending')",
            ),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="is_frozen",
            field=models.BooleanField(
                default=False,
                help_text="Response is frozen pending data subject request resolution",
            ),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="receipt_token",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Receipt token for data subject requests (pseudonymous surveys only)",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="surveyresponse",
            index=models.Index(
                fields=["receipt_token"], name="surveys_sur_receipt_a5cf9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="surveyresponse",
            index=models.Index(
                fields=["is_frozen"], name="surveys_sur_is_froz_e3f1f0_idx"
            ),
        ),
        migrations.AddField(
            model_name="datasubjectrequest",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who created this request record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_dsr_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="datasubjectrequest",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who resolved the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_dsr_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="datasubjectrequest",
            name="response",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific response if identified via receipt token",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="data_subject_requests",
                to="surveys.surveyresponse",
            ),
        ),
        migrations.AddField(
            model_name="datasubjectrequest",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_subject_requests",
                to="surveys.survey",
            ),
        ),
        migrations.AddIndex(
            model_name="datasubjectrequest",
            index=models.Index(fields=["status"], name="surveys_dat_status_8b4dd8_idx"),
        ),
        migrations.AddIndex(
            model_name="datasubjectrequest",
            index=models.Index(
                fields=["controller_deadline"], name="surveys_dat_control_f0cb22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datasubjectrequest",
            index=models.Index(
                fields=["receipt_token"], name="surveys_dat_receipt_cfe081_idx"
            ),
        ),
    ]
