# Generated by Django 5.2.9 on 2026-01-04 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0040_add_data_subject_request_support"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="dsr_warning_message",
            field=models.TextField(
                blank=True,
                help_text="Warning message shown to controller about pending DSRs",
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="has_pending_dsr",
            field=models.BooleanField(
                default=False,
                help_text="Survey has one or more pending data subject requests",
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="suspended_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When survey was suspended (if status=SUSPENDED)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="suspended_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Platform admin who suspended this survey",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suspended_surveys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="suspended_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason for suspension (e.g., 'Non-compliance with DSR')",
            ),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="freeze_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("controller", "Controller-initiated"),
                    ("platform", "Platform-initiated (DSR escalation)"),
                ],
                help_text="Whether freeze was controller or platform initiated",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("closed", "Closed"),
                    ("suspended", "Suspended (Data Subject Request)"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="frozen_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who froze this response",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="frozen_responses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ResponseFreezeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("freeze", "Frozen"), ("unfreeze", "Unfrozen")],
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("controller", "Controller-initiated"),
                            ("platform", "Platform-initiated (DSR escalation)"),
                        ],
                        help_text="Whether freeze was controller or platform initiated",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="Reason for the freeze/unfreeze action"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "data_subject_request",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked DSR if this freeze was due to a data subject request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="freeze_logs",
                        to="surveys.datasubjectrequest",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="freeze_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="freeze_logs",
                        to="surveys.surveyresponse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Response Freeze Log",
                "verbose_name_plural": "Response Freeze Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
