# Generated by Django 5.2.11 on 2026-02-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0041_add_dsr_escalation_and_freeze_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("add", "Add"),
                    ("remove", "Remove"),
                    ("update", "Update"),
                    ("create", "Create"),
                    ("invite", "Invite"),
                    ("key_recovery", "Key Recovery"),
                    ("login_success", "Successful Login"),
                    ("login_failed", "Failed Login Attempt"),
                    ("logout", "Logout"),
                    ("account_locked", "Account Locked"),
                    ("2fa_enabled", "2FA Enabled"),
                    ("2fa_disabled", "2FA Disabled"),
                    ("2fa_verified", "2FA Verification Success"),
                    ("2fa_failed", "2FA Verification Failed"),
                    ("backup_codes_generated", "Backup Codes Generated"),
                    ("backup_code_used", "Backup Code Used"),
                    ("password_changed", "Password Changed"),
                    ("password_reset", "Password Reset Requested"),
                    ("email_changed", "Email Address Changed"),
                    ("user_created", "User Account Created"),
                    ("user_deactivated", "User Account Deactivated"),
                    ("data_exported", "Data Exported"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="scope",
            field=models.CharField(
                choices=[
                    ("organization", "Organization"),
                    ("survey", "Survey"),
                    ("security", "Security"),
                    ("account", "Account"),
                    ("data_governance", "Data Governance"),
                ],
                max_length=20,
            ),
        ),
    ]
