# Generated by Django 5.2.11 on 2026-02-19 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0042_alter_auditlog_action_alter_auditlog_scope"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformKeyVersion",
            fields=[
                (
                    "version",
                    models.CharField(
                        help_text="Version identifier (e.g., 'v1', 'v2', 'v3')",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "vault_component",
                    models.BinaryField(
                        help_text="Vault-stored component of the split platform key (32 bytes). Useless alone - requires custodian component to reconstruct platform key."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this version was created",
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this version became active for new escrows",
                        null=True,
                    ),
                ),
                (
                    "retired_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this version stopped being used for new escrows. Still needed for decrypting old surveys.",
                        null=True,
                    ),
                ),
                (
                    "shares_last_rotated",
                    models.DateTimeField(
                        blank=True,
                        help_text="When Shamir shares were last rotated (for Option A: same platform key, new shares)",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Administrative notes about this version (e.g., reason for rotation)",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["activated_at"], name="surveys_pla_activat_680984_idx"
                    ),
                    models.Index(
                        fields=["retired_at"], name="surveys_pla_retired_c987ca_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSurveyKEKEscrow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vault_path",
                    models.CharField(
                        help_text="Path in Vault where encrypted KEK is stored",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "escrowed_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the KEK was escrowed"
                    ),
                ),
                (
                    "email_encrypted",
                    models.BooleanField(
                        default=True,
                        help_text="Whether user's email was encrypted in Vault for verification",
                    ),
                ),
                (
                    "recovered_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this KEK has been recovered (audit trail)",
                    ),
                ),
                (
                    "last_recovered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this KEK was last recovered",
                        null=True,
                    ),
                ),
                (
                    "last_recovered_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who last recovered this KEK",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recovered_keks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "platform_key_version",
                    models.ForeignKey(
                        help_text="Which platform key version was used to encrypt this KEK",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escrows",
                        to="surveys.platformkeyversion",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        help_text="Survey whose KEK is escrowed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kek_escrows",
                        to="surveys.survey",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User whose survey KEK is escrowed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_kek_escrows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Survey KEK Escrow",
                "verbose_name_plural": "User Survey KEK Escrows",
                "ordering": ["-escrowed_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-escrowed_at"],
                        name="surveys_use_user_id_5c3a46_idx",
                    ),
                    models.Index(
                        fields=["survey", "-escrowed_at"],
                        name="surveys_use_survey__eea429_idx",
                    ),
                    models.Index(
                        fields=["platform_key_version", "-escrowed_at"],
                        name="surveys_use_platfor_48a3b7_idx",
                    ),
                    models.Index(
                        fields=["vault_path"], name="surveys_use_vault_p_247cc9_idx"
                    ),
                ],
                "unique_together": {("user", "survey")},
            },
        ),
    ]
